import numpy as np
import pandas as pd
import sys
import os

import Distance_Estimator_Run_2
import OutcomeEstimator_Relists_Regrafts_2
import PostTransplantEstimater_2

#directory input
directory = sys.argv[1]

def create_new_stats(directory):
	"""
	This function generates new statistics based on the files in the 
	given directory.
	@Input:
		@directory: directory of output files generated by LivSim
	"""

	#generate travel statistics
	print("Generating Travel Statistics.")
	Distance_Estimator_Run_2.output_distance_data(directory)
	print("Travel Statistics Generated.")

	#generate relist/regraft statistics
	print("Generating Relist Statistics")
	OutcomeEstimator_Relists_Regrafts_2.estimate_relist_outcome(directory)
	print("Relist Statistics Generated")

	#generate post-transplant statistics
	#print("Generating Post Transplant Statistics")
	#PostTransplantEstimater_2.estimate_post_transplant_outcome(directory)
	#print("Post Transplant Statistics Generated")

if __name__ == "__main__":
	#validate the input
	if os.path.exists(directory) is False:
		print("Invalid directory")
		quit()

	#change directory to input files location
	os.chdir("C:/Users/kbui1993/Desktop/Postprocessing Input Files/")

	#create new statistics for given directory
	create_new_stats(directory)



